### ISSUE TITLE
Parsing error on Basic auth

### ISSUE THREAD

**Issue by kevinswiber** [coding-yogi/bombardier#25]
The Postman schema for authorizations is an array of:

```
{
  key: string,
  value: any,
  type: string
}
```

By default, a Postman v2.1 export will include, in the Basic auth key-value pairs, an entry for `showPassword` that has a boolean value.  This breaks under the current deserialization scheme.

**Comment by coding-yogi** [comment]
Could you please share an export of postman which fails at de-serialization for basic-auth? Also if `type` is `string`, shouldn't the `value` be of type `string` ?

**Comment by kevinswiber** [comment]
The code block above was referring to types, not values.  The `value` property could be any valid JSON value, while `key` and `type` will be strings.

Here's an exported Basic Auth example: https://gist.github.com/kevinswiber/252eccbe557b0bb76ecdaa15db31660c

**Comment by kevinswiber** [comment]
Here's the auth object:

```json
{
  "type": "basic",
  "basic": [
    {
      "key": "username",
      "value": "postman",
      "type": "string"
    },
    {
      "key": "password",
      "value": "password",
      "type": "string"
    },
    {
      "key": "showPassword",
      "value": false,
      "type": "boolean"
    }
  ]
}
```

**Comment by coding-yogi** [comment]
Got it, thanks, although not sure why my postman export doesn't show `showPassword` field in the export.
